insert into users values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 30, 'Harry', 'Potter');
insert into users values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 31, 'Ron', ' Weasley');
insert into users values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 29, 'Hermione', 'Granger');
insert into users values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 5, 100, 'Albus', 'Dumbledore');
insert into users values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 4, 56, 'Severus', 'Snape');
insert into users values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 34, 'Draco', 'Malfoy');
insert into users values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 44, 'Sirius', 'Black');
insert into users values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 72, 'Minerva', 'McGonagall');

insert into accounts values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA111', 1000.00, true, 1);
insert into accounts values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA112', 0.00, true, 1);
insert into accounts values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA113', 55.00, true, 1);
insert into accounts values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA211', 99.00, true, 1);
insert into accounts values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA311', 244.00, true, 1);
insert into accounts values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA312', 15.00, true, 1);
insert into accounts values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA411', 10000.00, true, 1);
insert into accounts values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA412', 1000.00, true, 1);
insert into accounts values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA413', 315.00, true, 1);
insert into accounts values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA414', 10.00, true, 1);
insert into accounts values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA415', 0.00, true, 1);
insert into accounts values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA511', 515.00, true, 1);
insert into accounts values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA512', 296.00, true, 1);
insert into accounts values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA513', 0.00, true, 1);
insert into accounts values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA514', 33.00, true, 1);
insert into accounts values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA611', 250.00, true, 1);
insert into accounts values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA612', 1000.00, true, 1);
insert into accounts values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA613', 0.00, true, 1);
insert into accounts values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA711', 1245.00, true, 1);
insert into accounts values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA712', 990.00, true, 1);
insert into accounts values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'UA811', 2000.00, true, 1);

insert into users_accounts values (1, 1);
insert into users_accounts values (1, 2);
insert into users_accounts values (1, 3);
insert into users_accounts values (2, 4);
insert into users_accounts values (3, 5);
insert into users_accounts values (3, 6);
insert into users_accounts values (4, 7);
insert into users_accounts values (4, 8);
insert into users_accounts values (4, 9);
insert into users_accounts values (4, 10);
insert into users_accounts values (4, 11);
insert into users_accounts values (5, 12);
insert into users_accounts values (5, 13);
insert into users_accounts values (5, 14);
insert into users_accounts values (5, 15);
insert into users_accounts values (6, 16);
insert into users_accounts values (6, 17);
insert into users_accounts values (6, 18);
insert into users_accounts values (7, 19);
insert into users_accounts values (7, 20);
insert into users_accounts values (8, 21);

insert into transaction_categories values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), true, 'MONEY_TRANSFER');
insert into transaction_categories values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), false, 'ACCOUNT_REPLENISHMENT');

insert into transactions values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 100.00, 1, 4);
insert into transactions values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 234.00, 9, 18);
insert into transactions values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 15.00, 4, 5);
insert into transactions values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 315.00, 10, 3);
insert into transactions values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 44.00, 7, 17);
insert into transactions values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10.00, 2, 17);
insert into transactions values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 191.00, 13, 11);
insert into transactions values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 95.00, 5, 8);
insert into transactions values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 500.00, 15, 2);
insert into transactions values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 211.00, 21, 7);
insert into transactions values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 77.00, 1, 3);
insert into transactions values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 116.00, 12, 2);
insert into transactions values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 443.00, 4, 10);
insert into transactions values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 94.00, 6, 4);
insert into transactions values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 111.00, 7, 21);
insert into transactions values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 79.00, 17, 4);
insert into transactions values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 257.00, 10, 3);
insert into transactions values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 840.00, 20, 16);
insert into transactions values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 25.00, 10, 18);
insert into transactions values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1000.00, 8, 20);
insert into transactions values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3.00, 10, 19);
insert into transactions values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 44.00, 15, 4);
insert into transactions values (23, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 91.00, 20, 7);
insert into transactions values (24, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 65.00, 2, 21);
insert into transactions values (25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 19.00, 12, 2);
insert into transactions values (26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 324.00, 12, 6);
insert into transactions values (27, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 50.00, 21, 5);
insert into transactions values (28, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 114.00, 19, 4);
insert into transactions values (29, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 297.00, 11, 18);
insert into transactions values (30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 80.00, 3, 17);

insert into transactions_register values(1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 2, 1);
insert into transactions_register values(2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1, 1, 2);
insert into transactions_register values(3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 2, 3);
insert into transactions_register values(4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2, 1, 6);
insert into transactions_register values(5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 2, 2);
insert into transactions_register values(6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3, 1, 3);
insert into transactions_register values(7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 4, 2, 5);
insert into transactions_register values(8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 4, 1, 1);
insert into transactions_register values(9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 5, 2, 4);
insert into transactions_register values(10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 5, 1, 6);
insert into transactions_register values(11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 6, 2, 1);
insert into transactions_register values(12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 6, 1, 6);
insert into transactions_register values(13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 7, 2, 5);
insert into transactions_register values(14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 7, 1, 4);
insert into transactions_register values(15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 8, 2, 3);
insert into transactions_register values(16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 8, 1, 5);
insert into transactions_register values(17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 9, 2, 6);
insert into transactions_register values(18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 9, 1, 1);
insert into transactions_register values(19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10, 2, 8);
insert into transactions_register values(20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10, 1, 4);
insert into transactions_register values(21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 11, 2, 1);
insert into transactions_register values(22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 11, 1, 1);
insert into transactions_register values(23, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 12, 2, 5);
insert into transactions_register values(24, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 12, 1, 1);
insert into transactions_register values(25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 13, 2, 2);
insert into transactions_register values(26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 13, 1, 4);
insert into transactions_register values(27, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 14, 2, 3);
insert into transactions_register values(28, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 14, 1, 2);
insert into transactions_register values(29, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 15, 2, 4);
insert into transactions_register values(30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 15, 1, 8);
insert into transactions_register values(31, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 16, 2, 6);
insert into transactions_register values(32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 16, 1, 2);
insert into transactions_register values(33, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 17, 2, 4);
insert into transactions_register values(34, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 17, 1, 1);
insert into transactions_register values(35, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 18, 2, 8);
insert into transactions_register values(36, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 18, 1, 6);
insert into transactions_register values(37, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 19, 2, 4);
insert into transactions_register values(38, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 19, 1, 6);
insert into transactions_register values(39, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 20, 2, 5);
insert into transactions_register values(40, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 20, 1, 7);
insert into transactions_register values(41, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 21, 2, 5);
insert into transactions_register values(42, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 21, 1, 7);
insert into transactions_register values(43, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 22, 2, 5);
insert into transactions_register values(44, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 22, 1, 2);
insert into transactions_register values(45, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 23, 2, 7);
insert into transactions_register values(46, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 23, 1, 4);
insert into transactions_register values(47, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 24, 2, 1);
insert into transactions_register values(48, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 24, 1, 8);
insert into transactions_register values(49, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 25, 2, 5);
insert into transactions_register values(50, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 25, 1, 1);
insert into transactions_register values(51, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 26, 2, 5);
insert into transactions_register values(52, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 26, 1, 3);
insert into transactions_register values(53, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 27, 2, 8);
insert into transactions_register values(54, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 27, 1, 3);
insert into transactions_register values(55, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 28, 2, 8);
insert into transactions_register values(56, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 28, 1, 2);
insert into transactions_register values(57, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 29, 2, 4);
insert into transactions_register values(58, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 29, 1, 6);
insert into transactions_register values(59, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 30, 2, 1);
insert into transactions_register values(60, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 30, 1, 6);

